# Generated by Django 3.1.5 on 2021-01-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20210118_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='user',
        ),
    ]
