# Generated by Django 3.1.5 on 2021-01-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20210119_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='name',
        ),
    ]
